export interface CityInfo {
    name: string;
    description: string;
    neighborhoods: string[];
    keywords: string[];
}

export const CITY_DATA: Record<string, CityInfo> = {
    hyderabad: {
        name: "Hyderabad",
        description: "Looking for **free classifieds in Hyderabad**? Freepo.in is your #1 destination to buy, sell, rent, and find jobs in Hyderabad without any cost. Access thousands of local listings from **Banjara Hills, Jubilee Hills, Gachibowli**, and more. Whether you need a used bike, a flat for rent, or a job vacancy in Hyderabad, our platform connects you directly with locals. Post your free ad today and reach millions of Hyderabadis instantly.",
        neighborhoods: [
            "Gachibowli",
            "Madhapur",
            "Banjara Hills",
            "Jubilee Hills",
            "Kukatpally",
            "Ameerpet",
            "Secunderabad",
            "Kondapur",
            "Hitech City",
            "Begumpet",
            "Dilsukhnagar",
            "Uppal",
            "Manikonda",
            "Himayatnagar",
            "Mehdipatnam",
        ],
        keywords: [
            "jobs in Hyderabad",
            "used cars in Hyderabad",
            "property for rent in Hyderabad",
            "used bikes for sale Hyderabad",
            "mobile phones Hyderabad",
            "furniture for sale Hyderabad",
            "part time jobs Hyderabad",
            "house for sale Hyderabad",
        ],
    },
    bangalore: {
        name: "Bangalore",
        description: "Find the best **free classifieds in Bangalore**. From IT jobs in **Whitefield** and **Electronic City** to apartments for rent in **Koramangala** and **Indiranagar**, Freepo.in has it all. Buy used cars, sell your old electronics, or hire staff in Bangalore for free. No login required to view listings. Join Bangalore's fastest growing community marketplace.",
        neighborhoods: [
            "Koramangala",
            "Indiranagar",
            "Whitefield",
            "Electronic City",
            "HSR Layout",
            "Jayanagar",
            "Malleswaram",
            "Marathahalli",
            "Hebbal",
            "BTM Layout",
            "JP Nagar",
            "Yelahanka",
        ],
        keywords: [
            "jobs in Bangalore",
            "flats for rent in Bangalore",
            "used laptops Bangalore",
            "second hand cars Bangalore",
            "bikes in Bangalore",
        ],
    },
    mumbai: {
        name: "Mumbai",
        description: "Mumbai's favorite free classifieds platform. Search **jobs in Mumbai**, flats on rent in **Andheri**, used cars in **Bandra**, and more. Post free ads in Mumbai to sell anything quickly. Connect with verified buyers and sellers across **Dadar, Powai, Navi Mumbai**, and **Thane**.",
        neighborhoods: [
            "Andheri",
            "Bandra",
            "Dadar",
            "Powai",
            "Thane",
            "Navi Mumbai",
            "Goregaon",
            "Malad",
            "Borivali",
            "Colaba",
            "Juhu",
            "Worli",
        ],
        keywords: [
            "jobs in Mumbai",
            "rentals in Mumbai",
            "used cars Mumbai",
            "second hand mobiles Mumbai",
        ],
    },
    delhi: {
        name: "Delhi",
        description: "The best place for **classifieds in Delhi**. Find government and private jobs, property for rent in **Saket** and **Laxmi Nagar**, or used cars in **Dwarka**. Freepo.in offers 100% free advertising for all Delhiites. Browse ads from **Rohini, Janakpuri, Connaught Place**, and NCR regions.",
        neighborhoods: [
            "Dwarka",
            "Rohini",
            "Saket",
            "Laxmi Nagar",
            "Janakpuri",
            "Connaught Place",
            "Vasant Kunj",
            "Karol Bagh",
            "Pitampura",
            "Hauz Khas",
        ],
        keywords: [
            "jobs in Delhi",
            "flats in Delhi",
            "used cars Delhi",
            "bikes for sale Delhi",
        ],
    },
    chennai: {
        name: "Chennai",
        description: "Post free ads in **Chennai**. Discover jobs in **OMR**, houses for rent in **Anna Nagar** and **Velachery**, or buy used bikes and cars. Freepo.in is Chennai's trusted local marketplace. Zero fees, instant approval.",
        neighborhoods: [
            "Anna Nagar",
            "T. Nagar",
            "Velachery",
            "Adyar",
            "OMR",
            "Tambaram",
            "Mylapore",
            "Guindy",
            "Porur",
            "Chromepet",
        ],
        keywords: [
            "jobs in Chennai",
            "houses for rent Chennai",
            "used cars Chennai",
            "second hand bikes Chennai",
        ],
    },
};
